"""add summaries table

Revision ID: 235a06afe07b
Revises: 3916f09fd1af
Create Date: 2025-06-18 00:58:13.678803

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '235a06afe07b'
down_revision: Union[str, None] = '3916f09fd1af'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('summaries',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('entity_id', sa.UUID(), nullable=False),
    sa.Column('source_type', sa.Enum('client_supplier_reviews', 'advisor_supplier_reviews', 'advisor_reviews', 'advisor_brand_reviews', name='source_type', schema='ai'), nullable=False),
    sa.Column('sources', postgresql.ARRAY(sa.UUID()), nullable=True),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('positive_tags', postgresql.ARRAY(sa.Text()), nullable=True),
    sa.Column('negative_tags', postgresql.ARRAY(sa.Text()), nullable=True),
    sa.Column('metadata', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='ai'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('summaries', schema='ai')
    op.execute('DROP TYPE ai.source_type')
    # ### end Alembic commands ###
