"""initial_add_ai_schema_add_content_enrichment_response_table_add_applied_at_col

Revision ID: 3916f09fd1af
Revises: 
Create Date: 2025-05-09 15:51:49.430238

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3916f09fd1af'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # MANUALLY: Add applied_at column to alembic_version table
    op.add_column('alembic_version', 
        sa.Column('applied_at', sa.DateTime(timezone=True), 
        server_default=sa.text('now()'), nullable=False),
        schema='ai'
    )
    
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('content_enrichment_response',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('metadata', sa.JSON(), nullable=True),
    sa.Column('function', sa.Enum('generate', 'shorten', 'elaborate', 'polish', 'change_my_tone', name='content_function', schema='ai'), nullable=False),
    sa.Column('tone', sa.Text(), nullable=True),
    sa.Column('user_instructions', sa.Text(), nullable=True),
    sa.Column('existing_text', sa.Text(), nullable=True),
    sa.Column('ai_response', sa.Text(), nullable=False),
    sa.Column('output_format', sa.Enum('text', 'html', name='output_format', schema='ai'), nullable=False),
    sa.Column('accepted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('failed', sa.Boolean(), nullable=False),
    sa.Column('ai_model', sa.Text(), nullable=True),
    sa.Column('latency_ms', sa.Integer(), nullable=True),
    sa.Column('cost_usd', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='ai'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('content_enrichment_response', schema='ai')
    # ### end Alembic commands ###
    
    # Remove applied_at column from alembic_version
    op.drop_column('alembic_version', 'applied_at', schema='ai')
